// <auto-generated />
using BulkyWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bulky.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240924145925_AddForginKeyOfcategoryforProduct")]
    partial class AddForginKeyOfcategoryforProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bulky.Models.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Charlie Green",
                            CategoryId = 0,
                            Description = "Learn the basics of machine learning.",
                            ISBM = "978-1-23-456789-0",
                            ListPrice = 44.990000000000002,
                            Price = 39.990000000000002,
                            Price100 = 34.990000000000002,
                            Price50 = 37.990000000000002,
                            Title = "Introduction to Machine Learning"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Bob Brown",
                            CategoryId = 0,
                            Description = "A comprehensive guide to data structures and algorithms.",
                            ISBM = "978-0-98-765432-1",
                            ListPrice = 59.990000000000002,
                            Price = 54.990000000000002,
                            Price100 = 49.990000000000002,
                            Price50 = 52.990000000000002,
                            Title = "Data Structures and Algorithms"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Alice Johnson",
                            CategoryId = 0,
                            Description = "Build modern web applications with ASP.NET Core.",
                            ISBM = "978-0-12-345678-9",
                            ListPrice = 39.990000000000002,
                            Price = 34.990000000000002,
                            Price100 = 29.989999999999998,
                            Price50 = 32.990000000000002,
                            Title = "Mastering ASP.NET Core"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Jane Smith",
                            CategoryId = 0,
                            Description = "Deep dive into advanced C# concepts.",
                            ISBM = "978-1-23-456789-7",
                            ListPrice = 49.990000000000002,
                            Price = 44.990000000000002,
                            Price100 = 39.990000000000002,
                            Price50 = 42.990000000000002,
                            Title = "Advanced C# Techniques"
                        },
                        new
                        {
                            Id = 5,
                            Author = "John Doe",
                            CategoryId = 0,
                            Description = "An introduction to C# programming.",
                            ISBM = "978-3-16-148410-0",
                            ListPrice = 29.989999999999998,
                            Price = 24.989999999999998,
                            Price100 = 19.989999999999998,
                            Price50 = 22.989999999999998,
                            Title = "C# Programming Basics"
                        });
                });

            modelBuilder.Entity("BulkyWeb.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "sci"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "his"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "ad"
                        });
                });

            modelBuilder.Entity("Bulky.Models.Models.Product", b =>
                {
                    b.HasOne("BulkyWeb.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
